apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: amq-bridge
  labels:
    strimzi.io/cluster: amq-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    # Topics and groups used by the HTTP clients through the HTTP Bridge
    # Change to match the topics used by your HTTP clients
    - resource:
        type: group
        name: amq-group
      operations:
        - Read
    - resource:
        type: topic
        name: amq-topic
        operations:
          - Create
          - Describe
          - Read
          - Write
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: amq-bridge
spec:
  replicas: 1
  bootstrapServers: amq-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
    - secretName: amq-cluster-cluster-ca-cert
      certificate: ca.crt
  authentication:
    type: scram-sha-512
    username: amq-bridge
    passwordSecret:
      secretName: amq-bridge
      password: password
  http:
    port: 8080
