apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker
metadata:
  name: amq-mirror-maker
spec:
  version: 3.4.0
  replicas: 1
  consumer:
    bootstrapServers: amq-source-cluster-kafka-bootstrap:9092
    groupId: amq-source-group-id
  producer:
    bootstrapServers: amq-target-cluster-kafka-bootstrap:9092
  include: ".*"
