apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: amq-test-topic
  labels:
    strimzi.io/cluster: amq-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
