apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: amq-cluster
spec:
  kafka:
    version: 3.4.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.4"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 200Mi
        deleteClaim: true
      - id: 1
        type: persistent-claim
        size: 200Mi
        deleteClaim: true
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 200Mi
      deleteClaim: true
  entityOperator:
    topicOperator: 
      resources:
        requests:
          cpu: 50m
          memory: 300Mi
        limits: 
          cpu: 100m
          memory: 500Mi
    userOperator: 
    # Adjust readinessProbe to let enough time for the useroperator to
    # boot when the resources are limited!
      readinessProbe:
        initialDelaySeconds: 30
        timeoutSeconds: 5
      livenessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 5
      resources:
        requests:
          cpu: 50m
          memory: 300Mi
        limits: 
          cpu: 100m
          memory: 500Mi
